#! /usr/bin/env node

var fs = require('fs'),
    _ = require('lodash'),
    prompt = require('prompt'),
    program = require('commander'),
    parse = require('./lib/parser.js'),
    interpret = require('./lib/interpreter.js'),
    filename,
    code, result;

// 'Runs a program written in the Kelp language. If <filename> is ommitted, an interactive shell will open where functions can be executed.'
program
    .version('1.0.0')
    .arguments('[filename]')
    .option('-p, --parse-only', 'Parse a Kelp program.')
    .option('-i, --interpret-only', 'Interpret a previously parsed Kelp program.')
    .option('-o, --output [filename]', 'Output the results to the specified file.')
    .action(function(file) {
        filename = file;
    })
    .parse(process.argv);

// If there is no filename, open an interactive propmt to execute different commands.
if (!filename) {
    var env = {};
    
    prompt.formatPrompt = function(parts) {
        return parts.message + parts.delim;
    }

    prompt.start({
        message: '>>',
        delimiter: ''
    });
    ask();

    function ask() {
        prompt.get(['cmd'], function(err, res) {
            if (err) {
                console.log();
                process.exit(0);
            }

            console.log(interpret(parse(res.cmd), env)[0]);
            ask();
        });
    }
} else {
    try {
         code = fs.readFileSync(filename, 'utf8');
    } catch (e) {
        console.log("Error reading file.");
        process.exit(1);
    }

    if (program.parseOnly) {
        result = JSON.stringify(parse(code), null, 2);
    } else {
        var output = program.interpretOnly ? interpret(JSON.parse(code)) : interpret(parse(code));

        result = output.filter(function(el) {
            return el !== undefined && el !== null;
        }).join('\n');
    }

    if (program.output) {
        var outFileName;

        if (typeof program.output === 'boolean') {
            console.log('Output filename is required.');
            process.exit(1);
        }

        fs.writeFile(program.output, result, function(err) {
            if (err) {
                console.log('Error saving file');
                process.exit(1);
            }
        });
    } else {
        console.log(result);
    }
}